spring:
  jpa:
    properties:
      hibernate:
        dialect:
          storage_engine: innodb
        enable_lazy_load_no_trans: 'true'
    defer-datasource-initialization: 'true'
    hibernate:
      ddl-auto: update
  datasource:
    password: admin123
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    url: jdbc:mysql://limitless.c0sz6hfqoyiu.us-east-1.rds.amazonaws.com:3306/limitless
  sql:
    init:
      mode: always
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
server:
  error:
    include-stacktrace: never
    include-binding-errors: always
    include-message: always
springdoc:
  use-management-port: 'false'
